--- The upstream pytest suite, recorded as data.
---
--- spec/data/upstream_cases.lua is generated by tools/gen_upstream_cases.py:
--- it wraps every public function of the reference implementation, runs the
--- whole of jpvanhal/inflection's test_inflection.py (455 parametrized cases)
--- and records each (arguments -> return value) pair. Because the upstream
--- suite passes, a recorded return value *is* the expected behaviour - which
--- means the cases cover everything the upstream tests cover, including
--- `test_uncountable_word_is_not_greedy`'s temporary UNCOUNTABLES mutation.
-- Resolve spec/ from this file's own location so the spec also runs under
-- busted, which does not load spec/run.lua.
local SPEC_DIR = (debug.getinfo(1, "S").source:sub(2):match("^(.*)[/\\][^/\\]*$")) or "spec"
local UNPACK = table.unpack or unpack -- luacheck: ignore 143

local support = dofile(SPEC_DIR .. "/support.lua")
support.setup_path()

local inflection = require("inflection")
local cases = dofile(support.data_file("upstream_cases.lua"))

local function display(args)
  local parts = {}
  for _, a in ipairs(args) do
    parts[#parts + 1] = type(a) == "string" and string.format("%q", a) or tostring(a)
  end
  return table.concat(parts, ", ")
end

-- Snapshot so each case can restore UNCOUNTABLES after mutating it.
local pristine = {}
for word in pairs(inflection.UNCOUNTABLES) do
  pristine[word] = true
end

local groups, order = {}, {}
for _, case in ipairs(cases) do
  local name = case[1]
  if not groups[name] then
    groups[name] = {}
    order[#order + 1] = name
  end
  groups[name][#groups[name] + 1] = case
end

for _, name in ipairs(order) do
  describe("upstream " .. name, function()
    for _, case in ipairs(groups[name]) do
      local _, fn, args, want, extra_uncountables = case[1], case[2], case[3], case[4], case[5]
      it(string.format("%s(%s) == %s", fn, display(args), string.format("%q", want)), function()
        if extra_uncountables then
          for _, word in pairs(pristine) do
            inflection.UNCOUNTABLES[word] = nil
          end
          for word in pairs(pristine) do
            inflection.UNCOUNTABLES[word] = true
          end
          for _, word in ipairs(extra_uncountables) do
            inflection.UNCOUNTABLES[word] = true
          end
        end
        local f = inflection[fn]
        assert(type(f) == "function", "no such exported function: " .. fn)
        assert.are.equal(want, f(UNPACK(args)))
      end)
    end
  end)
end

before_each(function()
  for word in pairs(inflection.UNCOUNTABLES) do
    inflection.UNCOUNTABLES[word] = nil
  end
  for word in pairs(pristine) do
    inflection.UNCOUNTABLES[word] = true
  end
end)
