#!/usr/bin/env python3
"""Generate lua/inflection/rules.lua from the reference implementation.

The rule tables are emitted in their original Python regex form so they stay
diffable against jpvanhal/inflection. inflection.regex compiles them at load
time; nothing is pre-translated here.

    ./tools/gen_rules.py [--upstream-src PATH]
"""
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import LUA_DIR, lua_long_string, reference, write  # noqa: E402

HEADER = """-- Rule tables copied verbatim from the reference implementation
-- (jpvanhal/inflection %s), which derives them from Rails' ActiveSupport
-- inflector. Generated by tools/gen_rules.py - do not edit by hand.
--
-- Patterns are kept in their original Python regex form so this file can be
-- diffed against upstream. inflection.regex compiles them to Lua patterns at
-- load time, and raises on any construct it cannot translate.
--
-- Upstream copyright (MIT): Copyright (C) 2012-2020 Janne Vanhala
"""


def emit(name, rules, indent="  "):
    lines = ["%s%s = {" % (indent, name)]
    for pattern, replacement in rules:
        lines.append('%s  { %s, %s },' % (indent, lua_long_string(pattern),
                                          lua_long_string(replacement)))
    lines.append("%s}," % indent)
    return lines


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--upstream-src", metavar="PATH",
                        help="use a source checkout instead of the installed package")
    args = parser.parse_args()

    inflection = reference(args.upstream_src)
    body = [HEADER % inflection.__version__, "return {"]
    body += emit("PLURALS", inflection.PLURALS)
    body += emit("SINGULARS", inflection.SINGULARS)
    uncountables = ", ".join(lua_long_string(w) for w in sorted(inflection.UNCOUNTABLES))
    body.append("  UNCOUNTABLES = { %s }," % uncountables)
    body.append("}")
    write(os.path.join(LUA_DIR, "rules.lua"), "\n".join(body) + "\n")
    print("PLURALS=%d SINGULARS=%d UNCOUNTABLES=%d"
          % (len(inflection.PLURALS), len(inflection.SINGULARS), len(inflection.UNCOUNTABLES)))


if __name__ == "__main__":
    main()
