#!/usr/bin/env python3
"""Generate lua/inflection/data.lua from Python's unicodedata module.

Three tables are emitted, each as a pair of parallel strings (a UTF-8 sequence
of code points, and newline-separated values indexed the same way) so the
generated file stays compact:

  NFKD   code point -> the ASCII part of its NFKD decomposition. Code points
         with no ASCII approximation are absent, which is exactly the
         `encode('ascii', 'ignore')` behaviour of transliterate().
  UPPER  code point -> str.upper() of that character (may be several chars,
         e.g. U+00DF -> "SS").
  LOWER  code point -> str.lower() of that character.

    ./tools/gen_unicode_data.py
"""
import os
import sys
import unicodedata

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import LUA_DIR, write  # noqa: E402

SEPARATOR = "\n"


def collect(transform):
    """Map every non-ASCII code point whose value the transform changes."""
    table = {}
    for code in range(0x80, 0x110000):
        char = chr(code)
        value = transform(char)
        if value and value != char:
            table[code] = value
    return table


def nfkd_ascii(char):
    decomposed = unicodedata.normalize("NFKD", char)
    return decomposed.encode("ascii", "ignore").decode("ascii") or None


def encode_table(table):
    codes = sorted(table)
    keys = "".join(chr(code) for code in codes)
    values = SEPARATOR.join(table[code] for code in codes)
    assert "]]" not in keys and "]]" not in values
    assert SEPARATOR not in keys
    for value in table.values():
        assert SEPARATOR not in value
    return keys, values


HEADER = """-- Unicode tables generated by tools/gen_unicode_data.py. Do not edit by hand.
--
-- Generated from CPython %s (Unicode database %s).
--
-- Both versions matter: these tables are a snapshot of the Unicode Character
-- Database, so regenerating under a Python whose unicodedata is older or newer
-- produces a different file. CI reads the version back out of the line above
-- and fails on a mismatch.
--
-- Each table is a pair of parallel strings: <NAME>_KEYS is a UTF-8 sequence of
-- code points in ascending order and <NAME>_VALS holds the corresponding values
-- separated by a newline, so entry i of KEYS maps to entry i of VALS.
-- inflection.utf8 expands them into hash tables once, at load time.
"""


def main():
    tables = [("NFKD", collect(nfkd_ascii)),
              ("UPPER", collect(lambda c: c.upper())),
              ("LOWER", collect(lambda c: c.lower()))]

    # Only major.minor is recorded: the tables are a function of the Unicode
    # database version, and embedding the patch level would make the output
    # differ between any two CPython builds that are otherwise identical.
    body = [HEADER % ("%d.%d" % sys.version_info[:2], unicodedata.unidata_version),
            "local M = {}"]
    for name, table in tables:
        keys, values = encode_table(table)
        body.append("")
        body.append("-- %d entries" % len(table))
        body.append("M.%s_KEYS = [==[%s]==]" % (name, keys))
        body.append("M.%s_VALS = [==[%s]==]" % (name, values))
    body.append("")
    body.append("return M")

    path = os.path.join(LUA_DIR, "data.lua")
    write(path, "\n".join(body) + "\n")
    print("entries: " + ", ".join("%s=%d" % (n, len(t)) for n, t in tables))


if __name__ == "__main__":
    main()
