#!/usr/bin/env python3
"""Record the upstream pytest suite as data-driven Lua assertions.

Rather than translating test_inflection.py by hand (and risking a translation
that agrees with this port instead of with upstream), the suite is *executed*
against the reference implementation with every public function wrapped. Each
recorded (arguments -> return value) pair is by definition the expected
behaviour, because the upstream assertions all pass.

This captures cases a hand-written port of the tests would miss, such as
test_uncountable_word_is_not_greedy temporarily adding an entry to
UNCOUNTABLES.

    pip install inflection==0.5.1
    ./tools/gen_upstream_cases.py --upstream-src /path/to/inflection-checkout

`--upstream-src` is required: the wheel does not ship test_inflection.py. Any
checkout of the tagged version works, e.g.

    git clone --branch 0.5.1 https://github.com/jpvanhal/inflection /tmp/inflection
"""
import argparse
import functools
import importlib
import importlib.util
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from common import SPEC_DATA_DIR, lua_string, reference, write  # noqa: E402
import common  # noqa: E402

PUBLIC_FUNCTIONS = [
    "camelize", "dasherize", "humanize", "ordinal", "ordinalize", "parameterize",
    "pluralize", "singularize", "tableize", "titleize", "transliterate", "underscore",
]

HEADER = """-- Assertions recorded from the reference implementation's own test suite.
-- Generated by tools/gen_upstream_cases.py - do not edit by hand.
--
-- Upstream: jpvanhal/inflection %(version)s, test_inflection.py
--   %(ncases)d parametrized cases executed, %(nfails)d failures
--   %(ncalls)d recorded calls, deduplicated to %(nrows)d assertions
--
-- Each row is { test name, function, arguments, expected result,
--               extra UNCOUNTABLES in effect (optional) }.
-- The last field reproduces tests that mutate inflection.UNCOUNTABLES.
"""


def install_pytest_stub():
    path = os.path.join(common.TOOLS_DIR, "pytest_stub.py")
    spec = importlib.util.spec_from_file_location("pytest", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    sys.modules["pytest"] = module
    return module


def run_suite(inflection):
    """Execute every test_* in test_inflection.py, recording all calls."""
    calls = []
    current = {"test": None}
    default_uncountables = set(inflection.UNCOUNTABLES)

    originals = {}

    def wrap(name):
        original = originals[name]

        @functools.wraps(original)
        def wrapper(*args, **kwargs):
            result = original(*args, **kwargs)
            calls.append({
                "test": current["test"],
                "fn": name,
                "args": list(args),
                "kwargs": kwargs,
                "out": result,
                "unc_extra": sorted(set(inflection.UNCOUNTABLES) - default_uncountables),
            })
            return result

        return wrapper

    for name in PUBLIC_FUNCTIONS:
        originals[name] = getattr(inflection, name)
        setattr(inflection, name, wrap(name))

    sys.argv = ["test_inflection"]
    module = importlib.import_module("test_inflection")

    executed = failures = 0
    for test_name in sorted(n for n in dir(module) if n.startswith("test_")):
        function = getattr(module, test_name)
        params = getattr(function, "_pytest_params", None)
        if params is None:
            cases = [{}]
        else:
            names, values = params
            cases = [dict(zip(names, v if isinstance(v, tuple) else (v,))) for v in values]
        for kwargs in cases:
            current["test"] = test_name
            executed += 1
            try:
                function(**kwargs)
            except BaseException as exc:  # noqa: BLE001 - report and keep going
                failures += 1
                print("  FAIL %s%r: %s" % (test_name, kwargs, exc), file=sys.stderr)

    if failures:
        sys.exit("%d of %d upstream cases failed; refusing to record golden data"
                 % (failures, executed))
    if any(c["kwargs"] for c in calls):
        sys.exit("a recorded call used keyword arguments, which the Lua data format cannot express")
    return calls, executed, default_uncountables


def emit_lua(calls, executed, version):
    seen, rows = set(), []
    for call in calls:
        key = json.dumps([call["fn"], call["args"], call["out"], call["unc_extra"]],
                         sort_keys=True, default=str)
        if key in seen:
            continue
        seen.add(key)

        def value(item):
            if isinstance(item, bool):
                return "true" if item else "false"
            if isinstance(item, int):
                return str(item)
            if isinstance(item, float):
                return repr(item)
            if item is None:
                return "nil"
            return lua_string(str(item))

        extra = ""
        if call["unc_extra"]:
            extra = ", { %s }" % ", ".join(lua_string(u) for u in call["unc_extra"])
        line = "  { %s, %s, { %s }, %s%s }," % (
            lua_string(call["test"]), lua_string(call["fn"]),
            ", ".join(value(a) for a in call["args"]), value(call["out"]), extra)
        # Sort key for a stable output order - see the note below.
        order = (call["test"], call["fn"],
                 json.dumps(call["args"], ensure_ascii=False),
                 json.dumps(call["out"], ensure_ascii=False),
                 tuple(call["unc_extra"]))
        rows.append((order, line))

    # Recording order follows the reference suite's execution order, which is not
    # reproducible: test_uncountability is parametrized over
    # `inflection.UNCOUNTABLES`, a set, so its order moves with PYTHONHASHSEED.
    # Sort instead, keeping rows grouped by the test that produced them.
    rows.sort(key=lambda row: row[0])
    rows = [line for _, line in rows]

    body = HEADER % {"version": version, "ncases": executed, "nfails": 0,
                     "ncalls": len(calls), "nrows": len(rows)}
    return body + "return {\n" + "\n".join(rows) + "\n}\n", len(rows)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--upstream-src", metavar="PATH", required=True,
                        help="checkout of jpvanhal/inflection containing test_inflection.py")
    parser.add_argument("--out", metavar="PATH",
                        default=os.path.join(SPEC_DATA_DIR, "upstream_cases.lua"))
    args = parser.parse_args()

    install_pytest_stub()
    inflection = reference(args.upstream_src)
    calls, executed, _ = run_suite(inflection)
    body, rows = emit_lua(calls, executed, inflection.__version__)
    write(args.out, body)
    print("upstream %s: %d cases executed, %d calls recorded, %d assertions emitted"
          % (inflection.__version__, executed, len(calls), rows))


if __name__ == "__main__":
    main()
